### ISSUE TITLE
Cannot Download Entire Folder

### ISSUE THREAD

**Issue by kangming06** [quasar/Quasar#1146] opened 2023-04-05 11:26 UTC
### Problem description

When I use `File Manager`, I am currently not able to download entire folders from the client side. Instead, I am limited to downloading files one by one, which can be time-consuming and inconvenient when I need to transfer multiple files within a folder.

### Proposal

To improve the experience and streamline the file transfer process, I propose implementing a feature that allows me to download entire folders from the client side.

**Comment by MaxXor** [comment] 2023-04-05 11:42
Duplicate of https://github.com/quasar/Quasar/issues/262

**Closed by MaxXor** 2023-04-05 11:42 UTC
Labels: enhancement
