### ISSUE TITLE
Auto execute on first connect

### ISSUE THREAD

**Issue by Milk8** [quasar/Quasar#1050] opened 2022-02-03 16:38 UTC
Would anyone have any solutions to auto executing a file to disk on client connection or any modified versions that have it? A lot of other rats use it though id like to use this since it’s more stable in my experience

**Comment by MaxXor** [comment] 2022-02-03 18:08
Duplicate of https://github.com/quasar/Quasar/issues/669

**Closed by MaxXor** 2022-02-03 18:08 UTC
