### ISSUE TITLE
 Please add file compression function

### ISSUE THREAD

**Issue by kuA35sSaasd** [quasar/Quasar#1158] opened 2023-04-18 10:06 UTC
### Problem description

When downloading many files, I need to download them one by one. It would be great if I could compress them into files and download them again

### Proposal

 Please add file compression function

**Comment by TheFaik** [comment] 2023-04-20 02:50
++++

**Comment by MaxXor** [comment] 2023-04-20 19:20
Duplicate of https://github.com/quasar/Quasar/issues/262 ("Download folders")

**Closed by MaxXor** 2023-04-20 19:20 UTC
Labels: enhancement
