### ISSUE TITLE
Soundcapture

### ISSUE THREAD

**Issue by Ral721chanel** [quasar/Quasar#935] opened 2021-03-03 20:12 UTC
Put a soundcapture to be able to listen the client

**Comment by BurntDog** [comment] 2021-03-03 23:19
It was removed but, available in version 1.3, look through threads to find link.

**Comment by Ral721chanel** [comment] 2021-03-04 05:02
An the remote chat?

**Comment by BurntDog** [comment] 2021-03-04 05:30
Did you look at the roadmap to see if it is being looked at? Max may consider that.

**Comment by MaxXor** [comment] 2021-03-04 16:15
Duplicate of https://github.com/quasar/Quasar/issues/135

**Closed by MaxXor** 2021-03-04 16:15 UTC
