### ISSUE TITLE
Record Audio

### ISSUE THREAD

**Issue by Keepslus** [quasar/Quasar#1174] opened 2023-06-12 12:59 UTC
### Problem description

I'm always frustrated when the user watches a youtube video, and I can't hear the sound in remote desktop.

### Proposal

I want an option to enable sound when using remote desktop.

**Comment by MaxXor** [comment] 2023-06-12 13:04
Duplicate of https://github.com/quasar/Quasar/issues/135

It's on the todo-list.

**Closed by MaxXor** 2023-06-12 13:04 UTC
Labels: enhancement
