### ISSUE TITLE
add download folder or compress folder in to zip option

### ISSUE THREAD

**Issue by mrx325** [quasar/Quasar#860] opened 2020-08-10 03:05 UTC
i like to have download a folder option or compress the folder in to zip file option which will help to reduce the time need to download large contents in a same folder otherwise we have to download files one by one

**Comment by MaxXor** [comment] 2020-08-10 18:49
Duplicate of https://github.com/quasar/Quasar/issues/262

**Closed by MaxXor** 2020-08-10 18:49 UTC
